name: 'Setup'
description: 'Setup Node.js, pnpm and install dependencies'

inputs:
  node-version:
    description: 'Node.js version'
    required: false
    default: '20'
  registry-url:
    description: 'Optional registry to set up for auth'
    required: false

runs:
  using: "composite"
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v4

    - name: Setup Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: ${{ inputs.registry-url }}
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install
      shell: bash
