name: CI

on:
  pull_request:
    branches: ['*']
  push:
    branches: ['main']

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build
        uses: ./.github/actions/build

      - name: Test
        uses: ./.github/actions/test
